# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

workspace 'OptimizeTutorialFinalApp'
project 'OptimizeTutorialFinalApp.xcodeproj'

target 'OptimizeTutorialFinalApp' do
  # Pods for OptimizeTutorialFinalApp
#=begin
  pod 'AEPCore'
  pod 'AEPLifecycle'
  pod 'AEPIdentity'
  pod 'AEPEdge'
  pod 'AEPEdgeConsent'
  pod 'AEPEdgeIdentity'
  pod 'AEPAssurance'
  pod 'AEPOptimize'
#=end
end
