# This is a basic workflow that is manually triggered

name: Update Versions

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        description: 'New version to use for the Messaging extension.  Example: 4.0.2'
        required: true
        
      branch:
        description: 'Branch to be used when updating versions'
        required: true
      
      core-dependency:
        description: 'If a version is provided, update AEPCore & AEPServices dependency in podspec and Package.swift'
        required: false
      
      edge-dependency:
        description: 'If a version is provided, update AEPEdge dependency in podspec and Package.swift'
        required: false

      edge-identity-dependency:
        description: 'If a version is provided, update AEPEdgeIdentity dependency in podspec and Package.swift'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-versions:
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3.1.0
      with:
        ref: ${{ github.event.inputs.branch }}
    
    - name: Update AEPMessaging
      run: (sh ./Script/update-versions.sh -n Messaging -v ${{ github.event.inputs.version }} -d "AEPCore ${{ github.event.inputs.core-dependency }}, AEPServices ${{ github.event.inputs.core-dependency }}, AEPEdge ${{ github.event.inputs.edge-dependency }}, AEPEdgeIdentity ${{ github.event.inputs.edge-identity-dependency }}")

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4.2.3
      with:
        token: ${{ github.token }}
        commit-message: Updating version to ${{ github.event.inputs.version }}.
        branch: version-${{ github.event.inputs.version }}-update
        delete-branch: true
        title: Updating version to ${{ github.event.inputs.version }}
        body: Updating version to ${{ github.event.inputs.version }}
